version: "3.0"

services:

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    entrypoint:
      - ./docker/install_requirements.sh
    command: python main.py
    volumes:
      - .:/code